version: '3.8'
services:
  refresh_base:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - refresh_base:/data
  auth_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '50051:50051'
    depends_on: [refresh_base]
volumes:
  refresh_base:
    driver: local